make the destroy more robust to avoid failure on destroy

diff --git a/.github/workflows/deploy-to-aks.yaml b/.github/workflows/deploy-to-aks.yaml
--- a/.github/workflows/deploy-to-aks.yaml
+++ b/.github/workflows/deploy-to-aks.yaml
@@ -121,7 +121,7 @@ jobs:
           export TF_VAR_AZURE_RESOURCE_GROUP="test_aks_${{ env.RESOURCE_GROUP }}"
           _NAME="aks${{ env.RESOURCE_GROUP }}"
           export TF_VAR_AZURE_STORAGE_ACCOUNT=${_NAME//[_-]/}
-          terraform destroy -auto-approve
+          terraform destroy -auto-approve || echo "Destroy process has failed somewhere. Check the logs"
 
       - name: Delete AKS cluster
         if: always()
